version: '3.1'

services:
  db:
    container_name: book-my-show-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data


#       version: '3.1'

# services:
#   db:
#     container_name: esforin-customer-portal-db
#     image: postgres:16
#     restart: unless-stopped
#     ports:
#       - ${POSTGRES_PORT}:5432
#     environment:
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#       # - ./volumes/db/init:/docker-entrypoint-initdb.d
